# Generated by Django 2.2.6 on 2021-07-26 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210725_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1, 'Min value is 1'), django.core.validators.MaxValueValidator(10, 'Max value is 10')]),
        ),
    ]
